# Generated by Django 4.1.2 on 2022-12-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="chech_in",
            new_name="check_in",
        ),
    ]
